version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret 
    ports:
      - "27017:27017" 
    volumes:
      - mongodb_data:/data/db 
    networks:
      - mongodb-network

 

networks:
  mongodb-network:
    driver: bridge 

volumes:
  mongodb_data: 
